name: example-job-trigger

on:
  workflow_run:
    workflows: ["pr-check"]
    types:
      - completed

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Parse event data
        env:
          EVENT_RUN: ${{ toJson(github.event.workflow_run) }}
        run: |
          printenv WORKFLOW_RUN > workflow_run.json
          echo "Workflow run ID: ${{ fromJson(env.EVENT_RUN).id }}"
      - name: Upload event run context
        uses: actions/upload-artifact@v4
        with:
          name: workflow-run-context
          path: workflow_run.json
